const CACHE_NAME = 'abil-portfolio-v2';
const urlsToCache = [
  '/',
  '/index.html',
  '/gallery.html',
  '/blog.html',
  '/blog1.html',
  '/blog2.html',
  '/blog3.html',
  '/contact.html',
  '/styles.css',
  '/script.js',
  '/favicon.ico',
  '/images/logo.png',
  '/images/Abil's Photo.jpg',
  '/images/photo1.jpg',
  '/images/photo2.jpg',
  '/images/photo3.jpg',
  '/images/achive1.jpg',
  '/images/achive2.jpg',
  '/images/achive3.jpg',
  '/images/Gambar1.jpg',
  '/images/Gambar2.jpg',
  '/images/Gambar3.jpg',
  '/images/Blog1.jpg',
  '/images/Blog2.jpg',
  '/images/Blog3.jpg',
  '/images/Sertif1.pdf',
  '/images/Sertif2.pdf',
  '/images/Sertif3.pdf',
];
// Rest of sw.js remains as previously provided